services:
  - type: web
    name: leadcity-mfb-website
    runtime: node
    env: node
    region: ohio
    plan: free
    branch: main
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

databases:
  - name: leadcity-mfb-db
    databaseName: leadcity_mfb
    user: leadcity_user
    plan: free
    region: ohio