services:
  - type: web
    name: leadcity-mfb-website
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: leadcity-mfb-db
          property: connectionString
    staticPublishPath: ./dist/public

databases:
  - name: leadcity-mfb-db
    databaseName: leadcity_mfb
    user: leadcity_user