services:
  - type: web
    name: leadcity-mfb-website
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: leadcity-mfb-db
          property: connectionString
      - key: PGHOST
        fromDatabase:
          name: leadcity-mfb-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: leadcity-mfb-db
          property: port
      - key: PGDATABASE
        fromDatabase:
          name: leadcity-mfb-db
          property: database
      - key: PGUSER
        fromDatabase:
          name: leadcity-mfb-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: leadcity-mfb-db
          property: password
    staticPublishPath: ./dist/public

databases:
  - name: leadcity-mfb-db
    databaseName: leadcity_mfb
    user: leadcity_user
    plan: free